# Generated by Django 4.2 on 2023-04-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_score',
            field=models.IntegerField(null=True),
        ),
    ]
