# Generated by Django 4.2 on 2023-04-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple_game', '0002_alter_user_best_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['best_score']},
        ),
    ]
